# Generated by Django 5.1.7 on 2025-04-17 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiQa",
            fields=[
                (
                    "qa_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("qa_content", models.CharField(max_length=100)),
                ("create_time", models.DateTimeField()),
                ("answers", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "ai_qa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocComment",
            fields=[
                (
                    "comment_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("comment", models.CharField(max_length=50)),
                ("create_time", models.DateTimeField()),
                ("status", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "doc_comment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "doc_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("doc_type", models.CharField(max_length=2)),
                ("title", models.CharField(max_length=20)),
                ("summary", models.CharField(blank=True, max_length=30, null=True)),
                ("text", models.CharField(blank=True, max_length=1000, null=True)),
                ("image_url", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "document",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocUserAction",
            fields=[
                (
                    "action_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("action_type", models.CharField(max_length=2)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "doc_user_action",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SleepChallenge",
            fields=[
                (
                    "challenge_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("challenge_title", models.CharField(max_length=20)),
                ("create_time", models.DateTimeField()),
                ("status", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "sleep_challenge",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserChallenge",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("update_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "user_challenge",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        db_comment="默认值需应用层设置为phone_number",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("user_type", models.CharField(max_length=2)),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_comment="0:男,1:女,2:其他", max_length=2, null=True
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.CharField(blank=True, max_length=40, null=True)),
                ("birthday", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("sleep_notice", models.CharField(blank=True, max_length=8, null=True)),
                ("wake_notice", models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SleepRecord",
            fields=[
                (
                    "record_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("record_time", models.DateTimeField()),
                ("sleep_time", models.DateTimeField()),
                ("wake_time", models.DateTimeField()),
                ("rating", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "sleep_record",
                "managed": True,
            },
        ),
    ]
