# Generated by Django 5.1.7 on 2025-04-23 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "doc_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("doc_type", models.CharField(max_length=2)),
                ("title", models.CharField(max_length=20)),
                ("summary", models.CharField(blank=True, max_length=30, null=True)),
                ("text", models.CharField(blank=True, max_length=1000, null=True)),
                ("image_url", models.CharField(blank=True, max_length=20, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "document",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        db_comment="默认值需应用层设置为phone_number",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("user_type", models.CharField(max_length=2)),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_comment="0:男,1:女,2:其他", max_length=2, null=True
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.CharField(blank=True, max_length=40, null=True)),
                ("birthday", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("sleep_notice", models.CharField(blank=True, max_length=8, null=True)),
                ("wake_notice", models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SleepRecord",
            fields=[
                (
                    "record_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("record_time", models.DateTimeField()),
                ("sleep_time", models.DateTimeField()),
                ("wake_time", models.DateTimeField()),
                ("rating", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "sleep_record",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SleepGroup",
            fields=[
                (
                    "group_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("group_name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="1", max_length=2)),
                ("avatar", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "sleep_group",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SleepChallenge",
            fields=[
                (
                    "challenge_id",
                    models.CharField(
                        default="1000000000",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("challenge_title", models.CharField(max_length=50)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "sleep_challenge",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DocUserAction",
            fields=[
                (
                    "action_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("action_type", models.CharField(max_length=2)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                (
                    "doc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "doc_user_action",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="document",
            name="post_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="myapp.user",
            ),
        ),
        migrations.CreateModel(
            name="DocComment",
            fields=[
                (
                    "comment_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("comment", models.CharField(max_length=50)),
                ("create_time", models.DateTimeField()),
                ("status", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.doccomment",
                    ),
                ),
                (
                    "doc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "doc_comment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("msg_type", models.CharField(default="0", max_length=2)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.sleepgroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "chat_history",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AiQa",
            fields=[
                (
                    "qa_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("qa_content", models.CharField(max_length=1000)),
                ("create_time", models.DateTimeField()),
                ("answers", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.user",
                    ),
                ),
            ],
            options={
                "db_table": "ai_qa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserChallenge",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="1000000000",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("completed_days", models.IntegerField(default=0)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.sleepchallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_challenge",
                "managed": True,
                "unique_together": {("user", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="ChallengeCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        default=1000000000,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkin_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user_challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.userchallenge",
                    ),
                ),
            ],
            options={
                "db_table": "challenge_checkin",
                "managed": True,
                "unique_together": {("user_challenge", "checkin_date")},
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(default="0", max_length=2)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.sleepgroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="myapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_group",
                "managed": True,
                "unique_together": {("group", "member")},
            },
        ),
    ]
