# Generated by Django 5.1.7 on 2025-04-21 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiqa",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="djangomigrations",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="doccomment",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="docuseraction",
            options={"managed": True},
        ),
    ]
